---
title: "PER get_popOverTime_noAP"
author: "Axel Luyten"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
load("testing/input/performance/PER get_popOverTime_noAP data.RData")
library(profvis) ; library(bestcost) ; library(tidyverse)
```

In the code of get_popOverTime_noAP(), the data frame "lifetable_withPop[["female"]] is grown in a loop
```{r evaluate single call of get_popOverTime_noAP}

profvis(output1 <- bestcost::get_popOverTime_noAP(
  lifetable_wPop = lifetable_withPop[["female"]],
  firstYear_lifetable = firstYear_lifetable,
  year_loopStart = firstYear_lifetable + 1
  )
, interval = 0.005, #rerun=TRUE,
prof_output = "testing/output/performance/get_popOverTime_noAP single call ORIGINAL.Rprof")
```

In the code of this optimized function the data frame (tibble) to be used in the loop is defined in advance.
```{r evaluate single call of get_popOverTime_noAP_opt}

profvis(output2 <- bestcost::get_popOverTime_noAP_opt(
  lifetable_wPop = lifetable_withPop[["female"]],
  firstYear_lifetable = firstYear_lifetable,
  year_loopStart = firstYear_lifetable + 1
  )
, interval = 0.005, #rerun=TRUE,
prof_output = "testing/output/performance/get_popOverTime_noAP single call OPTIMIZED.Rprof")
```
