---
title: "PER new method assesss_mortality_lifetable()"
author: "Axel Luyten"
date: "`r Sys.Date()`"
output: pdf_document
---

Here the new method (from the branch natural_deaths_as_input), where mortalities are calculated directly, is profiled.

```{r}
load("../testing/Performance/Compare ARE method with new method/workspace.RData")

library(profvis)
```

```{r}
# profvis(bestcost::assess_mortality_lifetable(
# 
#     exp = input_data_mortality$exp[2], # PM2.5=8.30=limit LRV CH, NO2=16.32=mean conc. in CH in 2019
#     cutoff = input_data_mortality$cutoff[2],   # PM2.5=5, NO2=10, i.e. WHO AQG 2021 
#     crf = unlist(input_data_mortality[2,
#                                       c("crf_mean", "crf_lowci", "crf_highci")]),
#     rr_increment = 10, 
#     crf_rescale_method = "loglinear",
#     first_age_pop = 0,
#     last_age_pop = 99,
#     interval_age_pop = 1,
#     prob_natural_death_male = lifetable_withPopulation[["male"]]$death_probability_natural,
#     prob_natural_death_female = lifetable_withPopulation[["female"]]$death_probability_natural,
#     prob_total_death_male = lifetable_withPopulation[["male"]]$death_probability_total,
#     prob_total_death_female = lifetable_withPopulation[["female"]]$death_probability_total,
#     population_male = lifetable_withPopulation[["male"]]$population, 
#     population_female = lifetable_withPopulation[["female"]]$population, 
#     year_of_analysis = 2019, 
#     pollutant = input_data_mortality$pollutant[2], 
#     age_group = input_data_mortality$outcome_group[2],
#     min_age = 20,
#     max_age = 0,
#     corrected_discount_rate = 0), 
#   prof_output = "../testing/Performance/Compare ARE method with new method/PER new method.Rprof",
# )

profvis(prof_input="../testing/Performance/2023-12-13 Compare ARE method with new method/PER new method.Rprof")
```



