---
title: "PER new method assesss_mortality_lifetable()"
author: "Axel Luyten"
date: "`r Sys.Date()`"
output: pdf_document
---

Here the function assess_mortality_lifetable() (date: 2023-12-20) is profiled.

```{r}
# First save package in current state as .zip file
#devtools::build(binary = TRUE, path = "../testing/Performance/2023-12-20 Implemented 'small changes'/")

# Load input data for function to be tested
load("../testing/Performance/2023-12-20 Implemented 'small changes'/data.Rdata")

# Install package (specify location where the .zip file was saved to)
install.packages("C:/Users/luytax/switchdrive/bestcost_euproject/r_package/testing/Performance/2023-12-20 Implemented 'small changes'/bestcost_0.0.0.1.zip",
                 repos=NULL,
                 type='source'
                 )

library(bestcost)

library(profvis)
```

```{r}
profvis(bestcost::assess_mortality_lifetable(

    exp = input_data_mortality$exp[2], # PM2.5=8.30=limit LRV CH, NO2=16.32=mean conc. in CH in 2019
    cutoff = input_data_mortality$cutoff[2],   # PM2.5=5, NO2=10, i.e. WHO AQG 2021 
    crf = unlist(input_data_mortality[2,
                                      c("crf_mean", "crf_lowci", "crf_highci")]),
    rr_increment = 10, 
    crf_rescale_method = "loglinear",
    first_age_pop = 0,
    last_age_pop = 99,
    interval_age_pop = 1,
    prob_natural_death_male = lifetable_withPopulation[["male"]]$death_probability_natural,
    prob_natural_death_female = lifetable_withPopulation[["female"]]$death_probability_natural,
    prob_total_death_male = lifetable_withPopulation[["male"]]$death_probability_total,
    prob_total_death_female = lifetable_withPopulation[["female"]]$death_probability_total,
    population_male = lifetable_withPopulation[["male"]]$population, 
    population_female = lifetable_withPopulation[["female"]]$population, 
    year_of_analysis = 2019, 
    info_pollutant = input_data_mortality$pollutant[2], 
    min_age = input_data_mortality$min_age[2],
    max_age = input_data_mortality$max_age[2],
    corrected_discount_rate = 0), 
  # prof_output = "../testing/Performance/2023-12-20 Implemented 'small changes'/PER.Rprof"
)

profvis(prof_input="../testing/Performance/2023-12-20 Implemented 'small changes'/PER.Rprof") # Current version

profvis(prof_input="../testing/Performance/2023-12-13 Compare ARE method with new method/PER new method.Rprof") # Old version

profvis(prof_input="../testing/Performance/2023-12-13 Compare ARE method with new method/PER ARE method.Rprof") # Initial version
```



